Repository concourse/fly, pull requests merged in 2018-05, with the labels that each got.

#216 allow custom resource type to be resolved when fly execute -j
  commands/internal/executehelpers/inputs.go
Labels: bug

#200 Try login and retry given command on authentication errors.
  integration/error_handling_test.go
  main.go
Labels: enhancement, fly

#227 add a flag to login to open the browser automatically
  commands/login.go
Labels: enhancement
